name: Build Executables

on:
  release:
    types:
      - published
  # push:
  #   branches:
  #     - main

jobs:
  build_linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executables for Linux
        run: python .github/workflows/build_executables.py

      - name: Create Release for Linux
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Butler  # Ścieżka do plików dołączanych do wydania
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

  build_mac:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executables for macOS
        run: python .github/workflows/build_executables.py

      - name: Create Release for macOS
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Butler.app  # Ścieżka do plików dołączanych do wydania
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

  build_windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executables for Windows
        run: python .github/workflows/build_executables.py

      - name: Create Release for Windows
        uses: softprops/action-gh-release@v1
        with:
          files:  dist/Butler.exe # Ścieżka do plików dołączanych do wydania
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
